name: demo workflow
on:
    push:
        branches:
        - main
jobs:
  ci-cd-pipeline:
    name: ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build with Gradle and Jib
        run: |
            ./gradlew \
            -Djib.to.image=devnoyo0123/argo-demo:${{ github.sha }} \
            jib \
            --info \
            --stacktrace \
            --no-daemon

