name: demo workflow
on:
    push:
        branches:
        - main
jobs:
  ci-cd-pipeline:
    name: ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Generate UUID
        id: generate-uuid
        run: echo "UUID=$(uuidgen)" >> $GITHUB_OUTPUT

      - name: Build with Gradle and Jib
        run: |
            ./gradlew \
            -PimageTag=${{ steps.generate-uuid.outputs.UUID }} \
            jib \
            --info \
            --stacktrace \
            --no-daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: devnoyo0123/argo-demo:${{ steps.generate-uuid.outputs.UUID }}

